"""Add username and additional user fields

Revision ID: 7a114e2dcf1b
Revises: 8e35d76f3a6a
Create Date: 2026-01-28 15:37:09.881910

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7a114e2dcf1b'
down_revision = '8e35d76f3a6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'company')
    op.drop_column('users', 'website')
    op.drop_column('users', 'location')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
