"""add_personal_info

Revision ID: 9f2d8c1a4b7e
Revises: c4bfa0de6950
Create Date: 2026-02-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2d8c1a4b7e'
down_revision = 'c4bfa0de6950'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'personal_info',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('full_name', sa.String(length=255), nullable=False),
		sa.Column('headline', sa.String(length=255), nullable=True),
		sa.Column('bio', sa.Text(), nullable=True),
		sa.Column('email', sa.String(length=255), nullable=True),
		sa.Column('phone', sa.String(length=50), nullable=True),
		sa.Column('location', sa.String(length=255), nullable=True),
		sa.Column('website', sa.String(length=2048), nullable=True),
		sa.Column('avatar_url', sa.String(length=2048), nullable=True),
		sa.Column('resume_url', sa.String(length=2048), nullable=True),
		sa.Column('social_links', sa.JSON(), nullable=False),
		sa.Column('metadata', sa.JSON(), nullable=False),
		sa.Column('visible', sa.Boolean(), nullable=False),
		sa.Column('order', sa.Integer(), nullable=False),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_personal_info_deleted_at'), 'personal_info', ['deleted_at'], unique=False)
	op.create_index(op.f('ix_personal_info_id'), 'personal_info', ['id'], unique=False)
	op.create_index(op.f('ix_personal_info_order'), 'personal_info', ['order'], unique=False)
	op.create_index(op.f('ix_personal_info_visible'), 'personal_info', ['visible'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_personal_info_visible'), table_name='personal_info')
	op.drop_index(op.f('ix_personal_info_order'), table_name='personal_info')
	op.drop_index(op.f('ix_personal_info_id'), table_name='personal_info')
	op.drop_index(op.f('ix_personal_info_deleted_at'), table_name='personal_info')
	op.drop_table('personal_info')
	# ### end Alembic commands ###
