"""add_skills

Revision ID: d2a91f7c6e4b
Revises: 9f2d8c1a4b7e
Create Date: 2026-02-28 17:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a91f7c6e4b'
down_revision = '9f2d8c1a4b7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'skills',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('title', sa.String(length=255), nullable=False),
		sa.Column('slug', sa.String(length=255), nullable=False),
		sa.Column('description', sa.String(length=1000), nullable=True),
		sa.Column('metadata', sa.JSON(), nullable=False),
		sa.Column('visible', sa.Boolean(), nullable=False),
		sa.Column('order', sa.Integer(), nullable=False),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_skills_deleted_at'), 'skills', ['deleted_at'], unique=False)
	op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
	op.create_index(op.f('ix_skills_order'), 'skills', ['order'], unique=False)
	op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
	op.create_index(op.f('ix_skills_visible'), 'skills', ['visible'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_skills_visible'), table_name='skills')
	op.drop_index(op.f('ix_skills_slug'), table_name='skills')
	op.drop_index(op.f('ix_skills_order'), table_name='skills')
	op.drop_index(op.f('ix_skills_id'), table_name='skills')
	op.drop_index(op.f('ix_skills_deleted_at'), table_name='skills')
	op.drop_table('skills')
	# ### end Alembic commands ###
